global:
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8889']
    # metric_relabel_configs:
    #   # Keep all metrics indefinitely - never mark as stale
    #   - source_labels: [__name__]
    #     action: keep
    #     regex: '.*'
